### ISSUE TITLE
README bare metal and pk start addresses

### ISSUE THREAD

**Issue by zwabbit** [ucb-bar/riscv-sodor#15]
The README lists the start addresses for bare metal and pk programs as at 0x2000 and 0x10000 respectively. Is there an extra 0 appended on there? Other documentation I've seen list 0x200 and 0x1000 and that's what the benchmarks committed to this repo also have.

**Comment by ccelio** [comment]
They keep changing it on me. -.-

0x1000 doesn't sound right though, that's not enough space to fit the entire proxy kernel between 0x0 to 0x1000.

**Comment by zwabbit** [comment]
I know you closed this, but where is this privileged spec 1.9? The latest one on the site is 1.7.

**Comment by ccelio** [comment]
The specification manual for 1.9 is not available. When it goes public, there will be an announcement on the riscv mailing list (I'm assuming it'll be public for the upcoming RISC-V workshop).

Until then, v1.9 is a work-in-progress with the prototyping occurring on a branch in riscv-tools and on the rocket-chip processor.

**Comment by zwabbit** [comment]
Alright, one last question pertaining to this, looking at the privileged spec, it states that the reset vector is 0x200 in section 3.1.9, so I get where the 0x200 value for bare metal programs might come from. Is the start address with pk just inferred based on the size of the pk itself or is this also canonically defined somewhere?

**Comment by ccelio** [comment]
Not inferred, just mandated. Which means the pk must fit below that address.

**Comment by zwabbit** [comment]
Where is that actually mandated? Granted I haven't read the privileged spec in fine detail, but I don't see any reference to that size limit. Or the Linux one for that matter.

**Comment by ccelio** [comment]
For Linux, none of this matters because the binary gets put into its own virtual memory space. You can have the binary start wherever you want, and Linux will jump to the proper address. 

For the proxy kernel, it gets to decide itself where it will jump to after it loads the user program. It has decided that it can fit within the first 0x10000 of memory, and so it decides it's going to start running binaries at 0x10000. This isn't a privileged ISA thing, it's an implementation thing.
