### ISSUE TITLE
why is this named after the beloved island home of thomas the tank engine and friends?

### ISSUE THREAD

**Issue by GregroxMun** [ucb-bar/riscv-sodor#61]
not an issue, i'm just curious.

**Comment by aswaterman** [comment]
The first RISC-V implementation was named Trainwreck because of its tight time budget and immature physical-design environment. Incidentally, Trainwreck is also the name of a strain of cannabis, which mellowed us towards naming things after trains instead of wrecks. The first successful RISC-V implementation was named Rocket, after Stephenson’s engine; the simulator was named Spike, after the golden spike used to mark the completion of the transcontinental railroad; and the educational cores are named as you’ve observed.
