### ISSUE TITLE
Clone of 'git@github.com:riscv/riscv-fesvr.git' into submodule path 'riscv-fesvr' failed

### ISSUE THREAD

**Issue by gitfoxi** [ucb-bar/riscv-sodor#8]
I think github no longer supports `git@github`. It needs `https://` or `ssh://` urls.

```
$ git submodule update --init --recursive
Cloning into 'riscv-fesvr'...
Saving password to keychain failed
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:riscv/riscv-fesvr.git' into submodule path 'riscv-fesvr' failed
```

**Comment by palmer-dabbelt** [comment]
github definately still supports SSH URLs.

You don't have a github public key.  Here's the first result from Google, which I think should tell you how to setup a SSH key.

http://stackoverflow.com/questions/21255438/permission-denied-publickey-fatal-could-not-read-from-remote-repository-whil

You should also be able to do something like

````
sed s#git@github.com:#git://github.com/#g -i .gitmodules
git submodule sync
````

to change your authentication method (I use a similar command to set everything to SSH URLs instead of HTTP, so I don't have to learn how to setup HTTP authentication).

**Comment by sbeamer** [comment]
To prevent this from happening in the future, we will be changing these URLs to https.
